package crypto

import (
	"crypto/ecdh"
	"crypto/rand"
	"crypto/x509"
	"encoding/json"
	"os"
	"testing"
)

// TestGenerateInteropFixture writes a real Go-produced grant envelope plus the
// reader private key that opens it, so reader client test suites can prove they
// decrypt what this package actually emits -- not what a JavaScript
// reimplementation of this package emits, which would agree with itself while
// both drifted from the spec.
//
// Skipped unless TREEHOUSE_INTEROP_OUT is set, so it never runs in CI.
func TestGenerateInteropFixture(t *testing.T) {
	out := os.Getenv("TREEHOUSE_INTEROP_OUT")
	if out == "" {
		t.Skip("set TREEHOUSE_INTEROP_OUT to regenerate the cross-language fixture")
	}

	keys, err := EnsureIn(&memoryStore{}, "")
	if err != nil {
		t.Fatalf("keys: %v", err)
	}
	readerPriv, err := ecdh.P256().GenerateKey(rand.Reader)
	if err != nil {
		t.Fatalf("reader key: %v", err)
	}

	const readerKeyID = "77777777-7777-7777-7777-777777777777"

	envelope, err := WrapMachineKey(keys, readerKeyID,
		b64.EncodeToString(readerPriv.PublicKey().Bytes()))
	if err != nil {
		t.Fatalf("wrap: %v", err)
	}

	var parsed map[string]any
	if err := json.Unmarshal([]byte(envelope), &parsed); err != nil {
		t.Fatalf("envelope: %v", err)
	}

	// A sealed diff produced by the same identity, so the reader client proves the whole
	// chain against Go output: unwrap the grant to MCK, derive K_wt from it and
	// the two paths, decrypt, gunzip, parse. A fixture covering only the grant
	// would leave the half that actually carries source code unverified.
	const (
		repoPath = "/src/app"
		wtPath   = "/src/app/feature-a"
	)
	// The field names the reader client consumes directly -- see ingest.FileDiffPayload
	// for why the sealed body is camelCase.
	diffJSON := []byte(`{"statSummary":"+3 -1 across 2 file(s)",` +
		`"files":[{"path":"src/main.go","staged":false,"statLine":"+3 -1","patch":"@@ -1 +1 @@\n-old\n+new\n","statOnly":false}]}`)
	sealed, err := SealDiff(keys, repoPath, wtPath, diffJSON)
	if err != nil {
		t.Fatalf("seal: %v", err)
	}

	fixture := map[string]any{
		"note":               "Generated by internal/crypto. Regenerate with TREEHOUSE_INTEROP_OUT.",
		"envelope":           parsed,
		"readerPrivatePkcs8": b64.EncodeToString(mustPKCS8(t, readerPriv)),
		"expectedMachineKey": b64.EncodeToString(keys.MCK),
		"sealedDiff":         sealed,
		"sealedDiffRepoPath": repoPath,
		"sealedDiffWtPath":   wtPath,
		"expectedDiffJSON":   string(diffJSON),
	}
	encoded, err := json.MarshalIndent(fixture, "", "  ")
	if err != nil {
		t.Fatalf("encode fixture: %v", err)
	}
	if err := os.WriteFile(out, append(encoded, '\n'), 0o644); err != nil {
		t.Fatalf("write fixture: %v", err)
	}
}

// mustPKCS8 exports the reader's private key so the JavaScript side can import
// it. Only a test fixture ever does this; the reader client's own key is non-extractable
// and never leaves the browser.
func mustPKCS8(t *testing.T, key *ecdh.PrivateKey) []byte {
	t.Helper()
	der, err := x509.MarshalPKCS8PrivateKey(key)
	if err != nil {
		t.Fatalf("marshal reader private key: %v", err)
	}
	return der
}
